"""empty message

Revision ID: ff672fcd050c
Revises: 
Create Date: 2023-11-04 05:03:47.742215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff672fcd050c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address_name', sa.String(length=150), nullable=True),
    sa.Column('address_street', sa.String(length=150), nullable=False),
    sa.Column('address_city', sa.String(length=150), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('expense',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('expense_time', sa.Time(), nullable=True),
    sa.Column('expense_type', sa.String(length=150), nullable=False),
    sa.Column('expense_dollar_amt', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('expense_mileage', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('expense_loc_start_id', sa.Integer(), nullable=True),
    sa.Column('expense_loc_end_id', sa.Integer(), nullable=True),
    sa.Column('expense_odom_start', sa.Integer(), nullable=True),
    sa.Column('expense_odom_end', sa.Integer(), nullable=True),
    sa.Column('expense_notes', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('address')
    op.drop_table('user')
    # ### end Alembic commands ###
